Update Jenkinsfile-Frontend

diff --git a/Jenkins-Pipeline-Code/Jenkinsfile-Frontend b/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
--- a/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
+++ b/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
@@ -99,6 +99,10 @@ pipeline {
                             echo $BUILD_NUMBER
                             imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
                             echo $imageTag
+                            if [ -z "$imageTag" ]; then
+                                echo "Error: Could not extract image tag."
+                                exit 1
+                            fi
                             sed -i "s/${AWS_ECR_REPO_NAME}:${imageTag}/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}/" deployment.yaml
                             git add deployment.yaml
                             git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
